events {
    worker_connections 1024;
}

http {
    include mime.types;

    upstream fastapi_app {
        server api:8000;
    }

    server {
        listen 80;
        server_name localhost;

        # Cabeceras de Seguridad HTTP (Ciberseguridad)
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin";
        add_header Permissions-Policy "camera=(), microphone=(), geolocation=()";
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' cdnjs.cloudflare.com www.googletagmanager.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com cdn.jsdelivr.net; font-src 'self' fonts.gstatic.com; img-src 'self' data: images.unsplash.com *.amazonaws.com; connect-src 'self' http://localhost:8000 http://127.0.0.1:8000 www.google-analytics.com;";

        # Sirviendo los estáticos y frontend 
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        # Redirigiendo llamadas API a FastAPI
        location /api/ {
            # Se rescribe para omitir el `/api` en FastAPI si es necesario
            rewrite ^/api/(.*) /$1 break;
            
            proxy_pass http://fastapi_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_addrs;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Subir el limite de payload para fotos
        client_max_body_size 10M;
    }
}
